"""Regression against golden data produced by the ORIGINAL healpy-based code.

``tests/golden/golden_v1.npz`` is generated by ``scripts/make_golden.py`` from the original
sources (see that script). These tests require NO healpy: they guard that the refactored,
healpy-free package reproduces scenes, noise, SRFs, dictionaries, joint-OMP supports and
metrics of the original implementation.
"""

from pathlib import Path

import numpy as np
import pytest

from gspwd import _healpix as hpx
from gspwd.kernels import maxdfcoeff
from gspwd.metrics import amplitude_errors, detectionmetrics, ecm, le, lr
from gspwd.omp import omp_multi_dict_shared
from gspwd.scenes import randomscene_rejection, scene_shd
from gspwd.sphere import gridangs, pix2vec
from gspwd.srf import generalized_srf, generalizeddict, pwd_dictionaries

GOLDEN = np.load(Path(__file__).parent / "golden" / "golden_v1.npz")
NUMPIX, NUMPEAK, MAXN, THR = 48, 768 * 4, 6, 1e-2
RESOL = hpx.nside2resol(hpx.npix2nside(NUMPIX))
THETA0 = [np.pi / (N + 0.5) for N in range(MAXN + 1)]
CELLS = [tuple(c) for c in GOLDEN["meta_cells"]]
REPS = int(GOLDEN["meta_reps"])
DET_KEYS = [str(k) for k in GOLDEN["meta_detection_keys"]]


@pytest.fixture(scope="module")
def dictionaries():
    return pwd_dictionaries(MAXN, THETA0, NUMPIX, NUMPEAK, True, hardbacknull=True)


def test_kernels_match_golden(dictionaries):
    _, _, optlist, _ = dictionaries
    for i, k in enumerate(optlist):
        np.testing.assert_allclose(k, GOLDEN[f"kernel_gspwd_N{i + 1}"], atol=1e-12, rtol=1e-10)


def test_dictionaries_match_golden(dictionaries):
    Dd, Ds, *_ = dictionaries
    np.testing.assert_allclose(Dd[1], GOLDEN["dict_gspwd_N2"], atol=1e-12)
    np.testing.assert_allclose(Ds[1], GOLDEN["dict_spwd_N2"], atol=1e-12)
    # dictionary construction is independent of the kernel scale convention
    G, _ = generalizeddict(maxdfcoeff(2), NUMPIX, NUMPEAK)
    np.testing.assert_allclose(G, GOLDEN["dict_spwd_N2"], atol=1e-12)


def _metrics_row(S, X, vecscene, amps):
    vecres = pix2vec(NUMPEAK, S).T
    d = detectionmetrics(vecres, vecscene, THETA=RESOL)
    row = [
        le(vecres, vecscene, THETA=RESOL),
        lr(vecres, vecscene, THETA=RESOL),
        ecm(vecres, vecscene, THETA=RESOL),
    ]
    row += [d[k] for k in sorted(d)]
    row.extend(amplitude_errors(vecres, X, vecscene, amps.flatten(), THETA=RESOL))
    return np.array(row, dtype=float)


@pytest.mark.parametrize("ci", range(len(CELLS)))
def test_cell_matches_golden(ci, dictionaries):
    SNR, NSOURCE, N = CELLS[ci]
    NSOURCE, N = int(NSOURCE), int(N)
    Dd, Ds, optlist, mdflist = dictionaries
    ths, phs = gridangs(NUMPIX)

    np.random.seed(42)  # the original reseeds once per (SNR, NSOURCE, N) cell
    for ind in range(REPS):
        tag = f"c{ci}_r{ind}"
        amps, thes, phis = randomscene_rejection(NSOURCE, AMIN=0.2, ANGMIN=(np.pi / max(3 * N, 4)))
        np.testing.assert_allclose(amps, GOLDEN[f"{tag}_amps"], rtol=1e-12, atol=1e-13)
        np.testing.assert_allclose(thes, GOLDEN[f"{tag}_thes"], rtol=1e-12, atol=1e-13)
        np.testing.assert_allclose(phis, GOLDEN[f"{tag}_phis"], rtol=1e-12, atol=1e-13)
        vecscene = np.stack(
            [np.sin(thes) * np.cos(phis), np.sin(thes) * np.sin(phis), np.cos(thes)], axis=1
        )
        truepix = hpx.ang2pix(hpx.npix2nside(NUMPEAK), thes, phis, nest=True)
        np.testing.assert_array_equal(truepix, GOLDEN[f"{tag}_truepix"])

        dsrf, ssrf = [], []
        noise_rng = np.random.default_rng([100 + ci, ind])  # as in scripts/make_golden.py
        for NORDER in range(1, N + 1):
            s = scene_shd(amps, thes, phis, NORDER, SNR, rng=noise_rng)
            np.testing.assert_allclose(s, GOLDEN[f"{tag}_shd{NORDER}"], atol=1e-12, rtol=1e-10)
            dsrf.append(generalized_srf(optlist[NORDER - 1], s, ths, phs, NORDER))
            ssrf.append(generalized_srf(mdflist[NORDER - 1], s, ths, phs, NORDER))
        np.testing.assert_allclose(dsrf[-1], GOLDEN[f"{tag}_dsrf_last"], atol=1e-10, rtol=1e-9)
        np.testing.assert_allclose(ssrf[-1], GOLDEN[f"{tag}_ssrf_last"], atol=1e-10, rtol=1e-9)

        D_d, D_s = Dd[:N], Ds[:N]
        runs = {
            "gm": omp_multi_dict_shared(
                dsrf,
                D_d,
                dsrf,
                D_d,
                max_iters=NUMPIX,
                return_support=True,
                aggregate="harmonic_mean",
                threshold=THR,
                snr=SNR,
            ),
            "sm": omp_multi_dict_shared(
                ssrf,
                D_s,
                ssrf,
                D_s,
                max_iters=NUMPIX,
                threshold=THR,
                snr=SNR,
                return_support=True,
                aggregate="harmonic_mean",
            ),
            "gs": omp_multi_dict_shared(
                [dsrf[-1]],
                [D_d[-1]],
                [dsrf[-1]],
                [D_d[-1]],
                max_iters=NUMPIX,
                threshold=THR,
                snr=SNR,
                return_support=True,
                aggregate="mean_abs",
            ),
            "ss": omp_multi_dict_shared(
                [ssrf[-1]],
                [D_s[-1]],
                [ssrf[-1]],
                [D_s[-1]],
                max_iters=NUMPIX,
                threshold=THR,
                snr=SNR,
                return_support=True,
                aggregate="mean_abs",
            ),
        }
        for name, (X, S, _R) in runs.items():
            gold_S = GOLDEN[f"{tag}_{name}_S"]
            stable = int(GOLDEN[f"{tag}_{name}_stable"])
            # The original joint OMP is chaotic once an order's residual hits machine precision
            # (see make_golden.stable_prefix_len): demand exact equality on the stable prefix only.
            np.testing.assert_array_equal(
                np.asarray(S)[:stable], gold_S[:stable], err_msg=f"{tag} {name} support prefix"
            )
            if stable < len(gold_S):
                continue  # tail atoms are rounding-noise driven in the original as well
            np.testing.assert_array_equal(np.asarray(S), gold_S, err_msg=f"{tag} {name} support")
            np.testing.assert_allclose(X, GOLDEN[f"{tag}_{name}_X"], atol=1e-9, rtol=1e-7)
            np.testing.assert_allclose(
                _metrics_row(S, X, vecscene, amps),
                GOLDEN[f"{tag}_{name}_metrics"],
                atol=1e-9,
                rtol=1e-7,
                err_msg=f"{tag} {name} metrics",
            )
